# Generated by Django 5.2.4 on 2025-07-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_student_remove_task_user_id_remove_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.student'),
        ),
    ]
